# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"PILImageLAB": "00_core.ipynb",
         "RGBToLAB": "00_core.ipynb",
         "TensorLAB": "00_core.ipynb",
         "decodes": "00_core.ipynb",
         "TensorL": "00_core.ipynb",
         "TensorAB": "00_core.ipynb",
         "Tuple_L_AB": "00_core.ipynb",
         "Split_L_AB": "00_core.ipynb",
         "AdjustType": "00_core.ipynb",
         "encodes": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://borisdayma.github.io/colorup/"

git_url = "https://github.com/borisdayma/colorup/tree/master/"

def custom_doc_links(name): return None
