# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/01_data.ipynb (unless otherwise specified).

__all__ = ['show_path_images']

# Cell
from fastai2.vision.all import *
from .core import *

# Cell
def show_path_images(path):
    "Display sample data from `path`"
    imgs = random.sample(list(get_image_files(path)), 20)
    imgs = L(PILImage.create(i) for i in imgs)
    show_images(imgs, nrows=5)